### ISSUE TITLE
3d survey lines to PIXCreateInstrument

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/PIXel-Toolbox#3]
Dear John, 

How do we assign a 3d line (x,y,z) from meat-space into pixel coordinates? I don't see the appropriate flag in the pixelToolboxManual.pdf for lines that have z values (i.e. 'PIXFixedZ')

e.g. 
`tid = PIXCreateInstrument( 'randomLine', 'line', PIXFixedZ+PIXUniqueOnly ); `
 `PIXAddLine( tid, 250, 39.5, 250, -150, 1.1, .1, 'x250line' );`

**Comment by jstanleyx** [comment]
If you have three dimensions for each point in a line,then PIXAddPoints is how to add those.

PIXFixedZ applies to the entire instrument. Everything you add to "tid" will have fixed Z.

**Comment by SRHarrison** [comment]
Thanks for the reply @jstanleyx . I'm not sure if I fully understand how to do this yet from your comment. 

Here's the steps that I think are needed, assuming that I start with a single 3d line defined by vectors xr, yr, and zr (in local coords):

` PIXForget;  ` 
` PIXSetStation('testStation');     ` 
` instID = [];` 
` %zmsl = 1.1; % not needed for 3d lines!` 
` name = 'surveyLine'         ` 
` tid = PIXCreateInstrument(name, 'survey', PIXUniqueOnly );` 
` PIXAddPoints(tid, xr, yr, zr, name );      ` 
` instID = [instID tid];` 
` pid = PIXCreatePackage('unalakleet', instID);` 
` e = matlab2Epoch(now);` 
` r = PIXCreateR( pid, e,zr); `  * Please read note below about this step!
` [geom, cam, ip] = lcpBeta2GeomCamIp( meta.globals.lcp, meta.betas );  ` 
` r = PIXParameterizeR( r, cam, geom, ip ); ` 
` r = PIXRebuildCollect( r ); ` 
` imagename = '1535238001.c2.timex.jpg';` 
` Im = imread(imagename); ` 
` showInsts(Im, r); ` 
 
 

NOTE*: I know here, I'm normally supposed to put in the tide or z value for the rect, but if I did, I found that PIXCreateR would overwrite the z values with tide. So if I changed line 84 of PIXCreateR to be `iz=tide.*ones(size(ix))` rather than `iz=tide*ones(size(ix))` then I could pass a vector of the z values in and then r.origz = iz is maintained. But now the r.tide is actually r.origz, so I probably wasn't supposed to do that. My lines in oblique FOV space now look correct, but I worry that I'm doing something incorrectly to get there....

What is the appropriate way to do this without modifying PIXCreateR?

**Comment by jstanleyx** [comment]
You should add the PIXFixedZ flag to PIXUniqueOnly in the create
instrument call. 

When I do this here, I see the correct z values in r. If you don't set
PIXFixedZ, then yes, the z values for the points is replaced by the
tide. 

I don't have the geoms or other info to finish building the collect, but
it should work
